### ISSUE TITLE
ログイン処理をREST_FRAMEWORKで作成する。

### ISSUE THREAD

**Issue by gotoh-poclab** [takasaki376/qastclone-backend#13]
from rest_framework import permissionsで作成

参考サイト
- 公式
https://www.django-rest-framework.org/api-guide/permissions/
- 参考サイト
https://runebook.dev/ja/docs/django_rest_framework/api-guide/permissions/index

**Comment by gotoh-poclab** [comment]
https://github.com/takasaki376/drf-next-tutorial
を参考にさせていただくと、

```
from rest_framework import permissions
class OwnerPermission(permissions.BasePermission):
    def has_object_permission(self, request, view, obj):
        # GETメソッドの場合は無条件の許可する
        if request.method in permissions.SAFE_METHODS:
            return True
        #  GETメソッド以外は、 owner とログインユーザが一致する場合のみ許可する
        return obj.owner.id == request.user.id
```

**Comment by takasaki376** [comment]
@gotoh-poclab さん
@mike3104 さん

タイトルと本文だけですが、質問データのＣＲＵＤ処理ができたところなので、次にログイン処理に着手していただけないでしょうか。
更新系の処理は、正確にはログイン後でないと、ＡＰＩだけのテストできないもできないです。

質問のＡＰＩがログイン有無で制御できている事が確認できたら、その質問のＡＰＩをベースに返信のＡＰＩを開発する方が効率がよいと思います。
