### ISSUE TITLE
カスタムユーザーモデルの作成

### ISSUE THREAD

**Issue by gotoh-poclab** [takasaki376/qastclone-backend#2]
- 新しくappを作成して、ユーザーのみのmodelを作成する。

メールアドレスでログイン可能
ニックネーム
パスワード
管理者かどうか

- djangoフレームワークで他が使用するものは残す方針
superuser
is_active
date_joined
などは残す。

- adminの画面
1. 表示可能(add_fieldsetsを変更して行う。)
email
password
date_joined
superuser
is_staff 
is_active

2. 追加や修正可能(fieldsetsを変更して行う)
email
password

- 補足
nicknameやプロフィール画像などの他のユーザー情報は、OneToOneFieldで新しくデータベースを作成する予定。

- 追加履歴
2021/05/31 djangoフレームワークで他が使用するものは残す方針に変更。
2021/06/02 admin画面に関して追記。
2021/06/05 admin画面の仕様詳細を記載

**Comment by gotoh-poclab** [comment]
usernameとpasswordは、Djangoのデフォルトのものを使用する。
その他は、以下のように設定

```
email = models.EmailField(unique=True)
nickname = models.models.CharField(max_length=255)
is_owner = models.BooleanField(default=False)

```

**Comment by takasaki376** [comment]
ログインに必要なのはemail とpasswordなので、usernameは標準の項目を使えないです。
たまたま同じ名前になるとしても、標準ではusernameがログインIDになってしまいます。

**Comment by gotoh-poclab** [comment]
この部分は、たかさきさんのものをたかさきさんのものをそのまま使わせてもらうのが良いのかなと思いました。

元は以下のサイトですかね。メールアドレスの変更とか、その後のメールを送るとかも書かれていますね。
https://blog.narito.ninja/detail/39/


```
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.contrib.auth.base_user import BaseUserManager

# =========================
# ユーザ定義（キーをメールアドレスにする）
# =========================
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model( email=email,   **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self,  email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user( email, password, **extra_fields)

    def create_superuser(self,  email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        # return self._create_user(username, email, password, **extra_fields)
        return self._create_user(email, password, **extra_fields)

# =========================
# ユーザ
# =========================
class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), blank=True,unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    objects = UserManager()

    EMAIL_FIELD = 'email' # fix
    USERNAME_FIELD = 'email' # fix

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)
```

**Comment by takasaki376** [comment]
上のURLを見て作ったように思います。

私の作成したのは、nicknameとかアバター画像のパスを持ってないです。
管理者のフラグも取得できず、あまり試行錯誤せずに対応しました。

ユーザモデルはメールアドレスとパスワードで認証できれば、他の項目は後から追加でも対応できるように思いますので、とりあえずは現在必要な情報で進めてもよいと思います。（私が開発していた頃はDB項目追加のやり方も知らない時でした）

**Comment by gotoh-poclab** [comment]
djangoのフレームワークのルールに基づくと
superuser
is_active
date_joined
は、残した方が良いのではないかと思うのですが、Issueを変更した方が良いのかなと思いました。

https://docs.djangoproject.com/ja/3.2/ref/contrib/auth/#django.contrib.auth.models.User.is_active

**Comment by takasaki376** [comment]
残しましょう。
superuserも、最初にcreatesuperuserのコマンド実行時に本来は使っているはずですね。
date_joinedは参照だけのようなので、あっても大丈夫です。

**Comment by gotoh-poclab** [comment]
ありがとうございます。Issueを書き直しました。

date_joinedは、ユーザー一覧のところを最近の人を上位に表示させる時に必要になってくると思いました。

**Comment by gotoh-poclab** [comment]
adminの画面に関して、何を表示させるかを確認しなおしたいと思いました。下記の内容でしょうか。

- 表示可能(add_fieldsetsを変更して行う。)
email
password
date_joined
superuser

- 追加や修正可能(fieldsetsを変更して行う)
email
password

書いたみたのですが、データベースに登録した項目とは、どこまで指しているんだろうと思いました。


あと、標準のUser Adminを利用が良いかもとのことですが、デフォルトで用意されているUserモデルを利用していると後からの変更が困難なので、最初にAbstractBaseUserモデルをカスタムしてUserモデルを自作することが推奨されております。
経験としても、最初にUser モデルを使用して後から書き換えたのですが、めちゃくちゃ大変でした。ここはやっておいた方が良いです。

https://docs.djangoproject.com/ja/3.0/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project
https://selfs-ryo.com/detail/compare_django_user_models

**Comment by takasaki376** [comment]
is_staff 、is_active でしょうか。
adminツールは、通常は使用しませんが、テスト時に変なデータになった場合に使用したり、今までは使用していない項目でもテストで参照してどういった動作にできるかを確認するなどの想定です。
テーブルに項目があるなら、修正できないとテスト時に使用できないです。

> あと、標準のUser Adminを利用が良いかもとのことですが、デフォルトで用意されているUserモデルを利用していると後からの変更が困難なので、最初にAbstractBaseUserモデルをカスタムしてUserモデルを自作することが推奨されております。

こちらは賛成です。
