### ISSUE TITLE
質問・メモの表示するものとして必要なものを考えて、coreの中のmodelに加える。

### ISSUE THREAD

**Issue by gotoh-poclab** [takasaki376/qastclone-backend#6]
データとして必要なものは、以下のもの

- タイトル
- テキスト
- 投稿者
- 登録時間
- 更新時間

以下のように記載
```
class Question(models.Model):
  title = models.CharField(max_length=100)  #＃ タイトル
  text = models.TextField()　##テキスト
  author = models.ForeignKey(User)  ## 投稿者
  registrationTimeAt = models.DateTimeField(auto_now_add=True)   ## 登録時間
  updatedAt = models.DateTimeField(auto_now=True)　 ## 更新時間
```

以下については、別途
- 優先(通常 or 至急)
- 匿名
- 解決済みかどうか

更新履歴
2021/06/05 １段回目に入れるものと変数名をキャメルケースにすることを記載。

**Comment by gotoh-poclab** [comment]
以下は、案です。

```
title = models.CharField(max_length=100)  #＃ タイトル
text = models.TextField()　##テキスト
owner = models.ForeignKey(User,  on_delete=models.CASCADE  )  ## 投稿者
priority = models.BooleanField(default=False)  ## 優先 (至急の場合にはTrue)
is_anonymous = models.BooleanField(default=False)      ## 匿名 (匿名の場合にはTrue)
created_at = models.DateTimeField(auto_now_add=True)   ## 投稿時間
updated_at = models.DateTimeField(auto_now=True)　 ## 更新時間
is_resolved = models.BooleanField(default=False) ## 解決ずみ(解決済みの時はTrue)
```

**Comment by gotoh-poclab** [comment]
投稿者のownerがいなくなったら消えるように、authorのところは

on_delete=models.CASCADE

にしておいた方が良いかもしれない。

**Comment by takasaki376** [comment]
当面は表示・更新に使うのはタイトル、テキストです。
バックエンド側だけで制御可能な投稿者、投稿時間、更新時間は最初から持っておいてよいと思います。

その他は、フロントエンド側で必要になった場合に追加しましょう。

投稿時間の名称ですが、今の名前だと質問データやメモデータにしか使用できません。フォルダやタグなど、他のテーブルと同じ意味になるように、登録時間として下さい。

**Comment by takasaki376** [comment]
> 投稿者のownerがいなくなったら消えるように、authorのところは
> on_delete=models.CASCADE
> にしておいた方が良いかもしれない。

アカウントが消えると、過去データを参照できなくなるので、データは残す方がよいと思います。
フロントエンド側で投稿者のデータがなくても表示できるような対応は必要になります。

**Comment by gotoh-poclab** [comment]
更新してみました。

```
title = models.CharField(max_length=100)  #＃ タイトル
text = models.TextField()　##テキスト
author = models.ForeignKey(User)  ## 投稿者
registration_time_at = models.DateTimeField(auto_now_add=True)   ## 登録時間
updated_at = models.DateTimeField(auto_now=True)　 ## 更新時間
```

**Comment by takasaki376** [comment]
Questionはこれでよいと思います。

[APIの仕様](https://github.com/takasaki376/qastclone-doc/blob/main/api/README.md)と[テーブルレイアウトの仕様](https://github.com/takasaki376/qastclone-doc/blob/main/db/README.md)をまとめて頂けないでしょうか。

qastclone-docの方にしたのはフロントエンドの方も参照すると思ったからです。
また、マージした際に自動的にデプロイする環境を作ると、設計書もマージ時にデプロイされるため、それは避けたいと思います。

**Comment by takasaki376** [comment]
ESLintの設定をして気づきましたが、項目名のアンダーバーを消して、アンダーバーの次の文字を大文字にして下さい。
updated_at 　→　updatedAt  など
 
参考）
今のアンダーバーで区切る書き方はスネークケースと呼ぶそうです。
QinMemoで使っているのが、キャメルケース、パスカルケースのいずれかです。
https://www.limecode.jp/entry/difference/camelcase-pascalcase

**Comment by gotoh-poclab** [comment]
キャメルケースに変更した案です。

```
class Question(models.Model):
  title = models.CharField(max_length=100)  #＃ タイトル
  text = models.TextField()　##テキスト
  author = models.ForeignKey(User)  ## 投稿者
  registrationTimeAt = models.DateTimeField(auto_now_add=True)   ## 登録時間
  updatedAt = models.DateTimeField(auto_now=True)　 ## 更新時間
```

**Comment by takasaki376** [comment]
了解しました。よろしくお願いします。

**Comment by gotoh-poclab** [comment]
mainに直接、間違ってpushしてしまいましたが、こちらのDB設計のテーブル名もキャメルけーすに変更しておきました。
https://github.com/takasaki376/qastclone-doc/blob/main/db/02_%E8%B3%AA%E5%95%8F.md
