### ISSUE TITLE
質問投稿画面（/ask）に関するurls.pyを作成する。

### ISSUE THREAD

**Issue by gotoh-poclab** [takasaki376/qastclone-backend#8]
以下のことができること。

- routerに呼び出すurlなどを設定する。
- urls.pyを作成するところは、このissueが最初なので関数の呼び出しなども設定する。
- 質問投稿画面（/ask）に関するserilizer.pyを作成する。
- 質問投稿画面（/ask）に関するviews.pyを作成する。

**Comment by gotoh-poclab** [comment]
設定したい関数名を、views.py でQuestionViewSetに設定して、urlを/ask/にしたいとすると、

```
# django.urlsからpathをimportする。どのサイトでも必要。デフォルトで書かれている。
from django.urls import path  
# rest_frameworkからroutersをimportする。rest_frameworkを使用する場合には、必要。
from rest_framework import routers 
# QuestionViewSetについては、自分で名前をつけるところ。今回はQuestionViewSetにする。
from .views import  QuestionViewSet 

# rest frameworkを使う時には、書く。
router = routers.DefaultRouter()　#routerを使用する時には書くもの。
# urlをaskにして、QuestionViewSetを使用するviewsにする時には、以下のように記載。
router.register('ask/', QuestionViewSet) #設定したいurl名にする。
```

になる予定。

**Comment by takasaki376** [comment]
APIの仕様を先に決めてしまいましょう。
https://github.com/takasaki376/qastclone-doc/blob/main/api/README.md

また、質問投稿に関連するAPIで一つのISSUEにして下さい。
今の分け方だと、テストができないです。

**Comment by gotoh-poclab** [comment]
今後は、url.py, serilizer.py, views.pyなどを１まとめにした区切りにしたIssueにしていきたいと思います。
他のissueはclosedにして、askに関してはこのissueにまとめました。
